# =========================
# NOMBRE DE LA APP Y PUERTO
# =========================
spring.application.name=gestiondeempresa
server.port=${PORT:8080}

# =========================
# DATASOURCE / BASE DE DATOS
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_de_empresa
spring.datasource.username=juanillux
spring.datasource.password=Akatsuki11.

# =========================
# JPA / HIBERNATE
# =========================
# No borra tablas, solo crea si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# DESACTIVAMOS SQL INIT DE SPRING
# =========================
spring.sql.init.mode=never